// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/docs/:versionProject?/:projectPage?/:page?": {
    params: {
      "versionProject"?: string;
      "projectPage"?: string;
      "page"?: string;
    };
  };
  "/404": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/docs/:versionProject?/:projectPage?/:page?" | "/404";
  };
  "home/home.tsx": {
    id: "home/home";
    page: "/";
  };
  "docs/docs.tsx": {
    id: "docs/docs";
    page: "/docs/:versionProject?/:projectPage?/:page?";
  };
  "404/404.tsx": {
    id: "404/404";
    page: "/404";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "home/home": typeof import("./app/home/home.tsx");
  "docs/docs": typeof import("./app/docs/docs.tsx");
  "404/404": typeof import("./app/404/404.tsx");
};