[versions]
# kotlin
kotlin = "2.3.0"
serialization = "1.9.0"
coroutines = "1.10.2"
vite = "16.5.0"

# Core
ktor = "3.3.3"
commonmark = "0.25.0"
caffeine = "3.1.8"

# Database
exposed = "1.1.1"
hikari = "6.3.0"
postgress = "42.7.7"

# Logging
log4j = "2.20.0"

# Other
commons = "1.8.0"
zip = "2.11.5"

# JS
wrapper = "1.0.0-pre.760"

[libraries]

# Database
exposed-dao = { module = "org.jetbrains.exposed:exposed-dao", version.ref = "exposed" }
exposed-jdbc = { module = "org.jetbrains.exposed:exposed-jdbc", version.ref = "exposed" }
exposed-json = { module = "org.jetbrains.exposed:exposed-json", version.ref = "exposed" }
exposed-migration = { module = "org.jetbrains.exposed:exposed-migration-jdbc", version.ref = "exposed" }
hikari = { module = "com.zaxxer:HikariCP", version.ref = "hikari" }
postgress = { module = "org.postgresql:postgresql", version.ref = "postgress" }

# Kotlin
serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }
serialization-hocon = { module = "org.jetbrains.kotlinx:kotlinx-serialization-hocon", version.ref = "serialization" }
serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "serialization" }
coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines"}

# Ktor server
ktor-server-core = { module = "io.ktor:ktor-server-core-jvm", version.ref = "ktor" }
ktor-server-cio = { module = "io.ktor:ktor-server-cio-jvm", version.ref = "ktor" }
ktor-server-cors = { module = "io.ktor:ktor-server-cors", version.ref = "ktor" }
ktor-server-auth = { module = "io.ktor:ktor-server-auth", version.ref = "ktor" }
ktor-server-resources = { module = "io.ktor:ktor-server-resources", version.ref = "ktor" }
ktor-server-negociation = { module = "io.ktor:ktor-server-content-negotiation", version.ref = "ktor" }
ktor-server-header = { module = "io.ktor:ktor-server-forwarded-header", version.ref = "ktor" }
ktor-server-call-logging = { module = "io.ktor:ktor-server-call-logging", version.ref = "ktor" }
ktor-server-call-logging-jvm = { module = "io.ktor:ktor-server-call-logging-jvm", version.ref = "ktor" }
ktor-server-caching-headers = { module = "io.ktor:ktor-server-caching-headers-jvm", version.ref = "ktor" }
ktor-server-default-headers = { module = "io.ktor:ktor-server-default-headers-jvm", version.ref = "ktor" }
ktor-server-status-pages = { module = "io.ktor:ktor-server-status-pages", version.ref = "ktor" }

# Common
ktor-resources = { module = "io.ktor:ktor-resources", version.ref = "ktor" }

# Ktor client
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-client-js = { module = "io.ktor:ktor-client-js", version.ref = "ktor" }
ktor-client-auth = { module = "io.ktor:ktor-client-auth", version.ref = "ktor" }
ktor-client-negociation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-client-resources = { module = "io.ktor:ktor-client-resources", version.ref = "ktor" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }

# Commonmark
commonmark = { module = "org.commonmark:commonmark", version.ref = "commonmark" }
commonmark-autolink = { module = "org.commonmark:commonmark-ext-autolink", version.ref = "commonmark" }
commonmark-strikethrough = { module = "org.commonmark:commonmark-ext-gfm-strikethrough", version.ref = "commonmark" }
commonmark-tables = { module = "org.commonmark:commonmark-ext-gfm-tables", version.ref = "commonmark" }
commonmark-list = { module = "org.commonmark:commonmark-ext-task-list-items", version.ref = "commonmark" }

# Logger
logger-core = { module = "org.apache.logging.log4j:log4j-core", version.ref = "log4j" }
logger-impl = { module = "org.apache.logging.log4j:log4j-slf4j2-impl", version.ref = "log4j" }

# Other
commons-cli = { module = "commons-cli:commons-cli", version.ref = "commons" }
caffeine = { module = "com.github.ben-manes.caffeine:caffeine", version.ref = "caffeine" }
zip = { module = "net.lingala.zip4j:zip4j", version.ref = "zip" }

# JS
wrapper-browser = { module = "org.jetbrains.kotlin-wrappers:kotlin-browser", version.ref = "wrapper" }

# build
build-serialization = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "kotlin" }
build-kotlin-multiplatform = { module = "org.jetbrains.kotlin.multiplatform:org.jetbrains.kotlin.multiplatform.gradle.plugin", version.ref = "kotlin" }
build-kotlin-js-plain-objects = { module = "org.jetbrains.kotlin.plugin.js-plain-objects:org.jetbrains.kotlin.plugin.js-plain-objects.gradle.plugin", version.ref = "kotlin" }
build-vite = { module = "io.github.turansky.kfc.application:io.github.turansky.kfc.application.gradle.plugin", version.ref = "vite" }

[plugins]
kotlin-js-objects = { id = "org.jetbrains.kotlin.plugin.js-plain-objects", version.ref = "kotlin" }
vite = { id = "io.github.turansky.kfc.application", version.ref = "vite" }
ktor = { id = "io.ktor.plugin", version.ref = "ktor" }

[bundles]
build = [
    "build-kotlin-multiplatform",
    "build-kotlin-js-plain-objects",
    "build-serialization",
    "build-vite",
]
commonmark = [
    "commonmark",
    "commonmark-autolink",
    "commonmark-strikethrough",
    "commonmark-tables",
    "commonmark-list",
]
ktor-server = [
    "ktor-server-core",
    "ktor-server-cio",
    "ktor-server-cors",
    "ktor-server-auth",
    "ktor-server-resources",
    "ktor-server-negociation",
    "ktor-server-header",
    "ktor-server-call-logging",
    "ktor-server-call-logging-jvm",
    "ktor-server-caching-headers",
    "ktor-server-default-headers",
    "ktor-server-status-pages",
]
ktor-client = [
    "ktor-client-core",
    "ktor-client-auth",
    "ktor-client-negociation",
    "ktor-client-json",
    "ktor-client-logging",
]
logger = [
    "logger-core",
    "logger-impl",
]
database = [
    "exposed-dao",
    "exposed-jdbc",
    "exposed-json",
    "exposed-migration",
    "hikari",
    "postgress",
]
